name: ashwanth_portfolio
description: "Personal portfolio website of Ashwanth V Praveen, Flutter Developer."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1

  # Routing
  go_router: ^16.2.0

  # Dependency Injection
  get_it: ^8.2.0
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets will be added later.
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Custom fonts will be added after we finalize typography.
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf